import { Document, Page, Text, View, Image, StyleSheet, Font } from "@react-pdf/renderer";
import { LOGO_PNG_BASE64 } from "./logo-base64";
import { CATEGORY_LABELS, STATUS_LABELS, stockStatus, type Item } from "@/lib/types";

const logoDataUri = `data:image/png;base64,${LOGO_PNG_BASE64}`;

Font.registerHyphenationCallback((word) => [word]);

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 9, fontFamily: "Helvetica", color: "#18181b" },
  header: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 14 },
  logo: { width: 36, height: 36 },
  orgName: { fontSize: 13, fontWeight: 700 },
  orgSub: { fontSize: 8, color: "#6b7280" },
  title: { fontSize: 12, fontWeight: 700, marginTop: 10 },
  subtitle: { fontSize: 9, color: "#6b7280", marginTop: 2, marginBottom: 12 },
  table: { borderTop: "1 solid #d6d6d0", borderLeft: "1 solid #d6d6d0" },
  tr: { flexDirection: "row" },
  thRow: { backgroundColor: "#f7f7f5" },
  th: {
    padding: 4,
    fontSize: 7.5,
    fontWeight: 700,
    color: "#6b7280",
    borderRight: "1 solid #d6d6d0",
    borderBottom: "1 solid #d6d6d0",
  },
  td: {
    padding: 4,
    fontSize: 8,
    borderRight: "1 solid #d6d6d0",
    borderBottom: "1 solid #d6d6d0",
  },
  colItem: { width: "26%" },
  colCategory: { width: "13%" },
  colShelf: { width: "10%" },
  colLocation: { width: "16%" },
  colStock: { width: "10%", textAlign: "right" },
  colMax: { width: "10%", textAlign: "right" },
  colStatus: { width: "15%" },
  signatures: { flexDirection: "row", gap: 24, marginTop: 36 },
  sigBlock: { flexGrow: 1, flexBasis: 0 },
  sigLine: { borderTop: "1 solid #18181b", marginBottom: 4, marginTop: 28 },
  sigLabel: { fontSize: 8, color: "#6b7280" },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 32,
    right: 32,
    fontSize: 7,
    color: "#9ca3af",
    textAlign: "center",
  },
});

export interface CountSheetReportInput {
  items: Item[];
  generatedBy: string;
}

export function CountSheetDocument({ items, generatedBy }: CountSheetReportInput) {
  const asOf = new Date().toLocaleDateString("en-PH", { dateStyle: "medium" });
  const sorted = [...items].sort(
    (a, b) => a.location.localeCompare(b.location) || a.name.localeCompare(b.name),
  );

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Image style={styles.logo} src={logoDataUri} />
          <View>
            <Text style={styles.orgName}>Northern Luzon Mission</Text>
            <Text style={styles.orgSub}>Inventory &amp; Dispensing System</Text>
          </View>
        </View>

        <Text style={styles.title}>Inventory Count Sheet</Text>
        <Text style={styles.subtitle}>
          As of {asOf} · generated{" "}
          {new Date().toLocaleString("en-PH", { dateStyle: "medium", timeStyle: "short" })}
        </Text>

        <View style={styles.table}>
          <View style={[styles.tr, styles.thRow]} fixed>
            <Text style={[styles.th, styles.colItem]}>Item</Text>
            <Text style={[styles.th, styles.colCategory]}>Category</Text>
            <Text style={[styles.th, styles.colShelf]}>Shelf</Text>
            <Text style={[styles.th, styles.colLocation]}>Location</Text>
            <Text style={[styles.th, styles.colStock]}>On hand</Text>
            <Text style={[styles.th, styles.colMax]}>Max</Text>
            <Text style={[styles.th, styles.colStatus]}>Status</Text>
          </View>
          {sorted.map((item) => (
            <View style={styles.tr} key={item.id} wrap={false}>
              <Text style={[styles.td, styles.colItem]}>{item.name}</Text>
              <Text style={[styles.td, styles.colCategory]}>{CATEGORY_LABELS[item.category]}</Text>
              <Text style={[styles.td, styles.colShelf]}>{item.shelf}</Text>
              <Text style={[styles.td, styles.colLocation]}>{item.location}</Text>
              <Text style={[styles.td, styles.colStock]}>
                {item.stock} {item.unit}
              </Text>
              <Text style={[styles.td, styles.colMax]}>{item.maxStock}</Text>
              <Text style={[styles.td, styles.colStatus]}>{STATUS_LABELS[stockStatus(item)]}</Text>
            </View>
          ))}
        </View>

        <View style={styles.signatures}>
          <View style={styles.sigBlock}>
            <Text style={styles.sigLine} />
            <Text style={styles.sigLabel}>Counted by</Text>
          </View>
          <View style={styles.sigBlock}>
            <Text style={styles.sigLine} />
            <Text style={styles.sigLabel}>Verified by</Text>
          </View>
        </View>

        <Text style={styles.footer} fixed>
          Generated by {generatedBy} · Northern Luzon Mission Inventory System
        </Text>
      </Page>
    </Document>
  );
}
